Fix examples/spatialaudio/audiopanning to run
The enum Loops provides constants ( Infinite = -1, Once = 1) to be
passed to functions taking int. Change the type to IntEnum to enable
this.

Fixes:
 self._sound.setLoops(QSpatialSound.Infinite)
TypeError: 'PySide6.QtSpatialAudio.QSpatialSound.setLoops' called with wrong argument types:
  PySide6.QtSpatialAudio.QSpatialSound.setLoops(Loops)

Change-Id: Ife4d7a6197220f13a2d59547d8a6b3a503eaff55
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>
(cherry picked from commit 8ed5cf2c5cccfc06347498e58104a17d65e88379)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>